// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheStockedKitchen.Db;

#nullable disable

namespace TheStockedKitchen.DB.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20230525164823_RecipeMade")]
    partial class RecipeMade
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TheStockedKitchen.Data.Model.FoodStock", b =>
                {
                    b.Property<int>("FoodStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FoodStockId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodStockId"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Category");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Image");

                    b.Property<bool>("IncludedInRecipeSearch")
                        .HasColumnType("bit")
                        .HasColumnName("IncludedInRecipeSearch");

                    b.Property<DateTime?>("LastEditedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastEditedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<double>("Quantity")
                        .HasColumnType("float")
                        .HasColumnName("Quantity");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Unit");

                    b.Property<string>("UnitAbbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UnitAbbreviation");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("User");

                    b.HasKey("FoodStockId");

                    b.ToTable("FoodStock", "dbo");
                });

            modelBuilder.Entity("TheStockedKitchen.Data.Model.RecipeMade", b =>
                {
                    b.Property<int>("RecipeMadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RecipeMadeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeMadeId"), 1L, 1);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Image");

                    b.Property<int>("SpoonacularRecipeId")
                        .HasColumnType("int")
                        .HasColumnName("SpoonacularRecipeId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("User");

                    b.HasKey("RecipeMadeId");

                    b.ToTable("RecipeMade", "dbo");
                });

            modelBuilder.Entity("TheStockedKitchen.Data.Model.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitId"), 1L, 1);

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Abbreviation");

                    b.Property<bool>("AllowedInDropDown")
                        .HasColumnType("bit")
                        .HasColumnName("AllowedInDropDown");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("UnitId");

                    b.ToTable("Unit", "dbo");

                    b.HasData(
                        new
                        {
                            UnitId = 1,
                            Abbreviation = "MG",
                            AllowedInDropDown = false,
                            Name = "Milligrams"
                        },
                        new
                        {
                            UnitId = 2,
                            Abbreviation = "UG",
                            AllowedInDropDown = false,
                            Name = "Micrograms"
                        },
                        new
                        {
                            UnitId = 3,
                            Abbreviation = "G",
                            AllowedInDropDown = true,
                            Name = "Grams"
                        },
                        new
                        {
                            UnitId = 4,
                            Abbreviation = "IU",
                            AllowedInDropDown = false,
                            Name = "International Units"
                        },
                        new
                        {
                            UnitId = 5,
                            Abbreviation = "kJ",
                            AllowedInDropDown = false,
                            Name = "Kilojoules"
                        },
                        new
                        {
                            UnitId = 6,
                            Abbreviation = "KCAL",
                            AllowedInDropDown = false,
                            Name = "Calories"
                        },
                        new
                        {
                            UnitId = 7,
                            Abbreviation = "OZ",
                            AllowedInDropDown = true,
                            Name = "Ounces"
                        },
                        new
                        {
                            UnitId = 8,
                            Abbreviation = "C",
                            AllowedInDropDown = true,
                            Name = "Cups"
                        },
                        new
                        {
                            UnitId = 9,
                            Abbreviation = "LB",
                            AllowedInDropDown = true,
                            Name = "Pounds"
                        },
                        new
                        {
                            UnitId = 10,
                            Abbreviation = "TBSP",
                            AllowedInDropDown = true,
                            Name = "Tablespoons"
                        },
                        new
                        {
                            UnitId = 11,
                            Abbreviation = "TSP",
                            AllowedInDropDown = true,
                            Name = "Teaspoons"
                        },
                        new
                        {
                            UnitId = 12,
                            Abbreviation = "FL OZ",
                            AllowedInDropDown = true,
                            Name = "Fluid Ounces"
                        },
                        new
                        {
                            UnitId = 13,
                            Abbreviation = "PT",
                            AllowedInDropDown = true,
                            Name = "Pints"
                        },
                        new
                        {
                            UnitId = 14,
                            Abbreviation = "QT",
                            AllowedInDropDown = true,
                            Name = "Quarts"
                        },
                        new
                        {
                            UnitId = 15,
                            Abbreviation = "GAL",
                            AllowedInDropDown = true,
                            Name = "Gallons"
                        },
                        new
                        {
                            UnitId = 16,
                            Abbreviation = "W",
                            AllowedInDropDown = true,
                            Name = "Whole"
                        });
                });

            modelBuilder.Entity("TheStockedKitchen.Data.Model.UnitConversion", b =>
                {
                    b.Property<int>("UnitConversionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UnitConversionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitConversionId"), 1L, 1);

                    b.Property<string>("CompareUnitAbbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CompareUnitAbbreviation");

                    b.Property<double>("CompareUnitAmount")
                        .HasColumnType("float")
                        .HasColumnName("CompareUnitAmount");

                    b.Property<string>("UnitAbbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UnitAbbreviation");

                    b.Property<double>("UnitAmount")
                        .HasColumnType("float")
                        .HasColumnName("UnitAmount");

                    b.HasKey("UnitConversionId");

                    b.ToTable("UnitConversion", "dbo");

                    b.HasData(
                        new
                        {
                            UnitConversionId = 1,
                            CompareUnitAbbreviation = "G",
                            CompareUnitAmount = 1.0,
                            UnitAbbreviation = "G",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 2,
                            CompareUnitAbbreviation = "OZ",
                            CompareUnitAmount = 0.035274,
                            UnitAbbreviation = "G",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 3,
                            CompareUnitAbbreviation = "C",
                            CompareUnitAmount = 0.0042267528380000004,
                            UnitAbbreviation = "G",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 4,
                            CompareUnitAbbreviation = "LB",
                            CompareUnitAmount = 0.00220462,
                            UnitAbbreviation = "G",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 5,
                            CompareUnitAbbreviation = "TBSP",
                            CompareUnitAmount = 0.067628045400000003,
                            UnitAbbreviation = "G",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 6,
                            CompareUnitAbbreviation = "TSP",
                            CompareUnitAmount = 0.20288413620000001,
                            UnitAbbreviation = "G",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 7,
                            CompareUnitAbbreviation = "FL OZ",
                            CompareUnitAmount = 29.57,
                            UnitAbbreviation = "G",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 8,
                            CompareUnitAbbreviation = "PT",
                            CompareUnitAmount = 0.0021133764190000002,
                            UnitAbbreviation = "G",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 9,
                            CompareUnitAbbreviation = "QT",
                            CompareUnitAmount = 0.0010566882090000001,
                            UnitAbbreviation = "G",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 10,
                            CompareUnitAbbreviation = "GAL",
                            CompareUnitAmount = 0.00026417205200000003,
                            UnitAbbreviation = "G",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 11,
                            CompareUnitAbbreviation = "G",
                            CompareUnitAmount = 28.349499999999999,
                            UnitAbbreviation = "OZ",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 12,
                            CompareUnitAbbreviation = "OZ",
                            CompareUnitAmount = 1.0,
                            UnitAbbreviation = "OZ",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 13,
                            CompareUnitAbbreviation = "C",
                            CompareUnitAmount = 0.119826427325,
                            UnitAbbreviation = "OZ",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 14,
                            CompareUnitAbbreviation = "LB",
                            CompareUnitAmount = 0.0625,
                            UnitAbbreviation = "OZ",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 15,
                            CompareUnitAbbreviation = "TBSP",
                            CompareUnitAmount = 2.0,
                            UnitAbbreviation = "OZ",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 16,
                            CompareUnitAbbreviation = "TSP",
                            CompareUnitAmount = 6.0,
                            UnitAbbreviation = "OZ",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 17,
                            CompareUnitAbbreviation = "FL OZ",
                            CompareUnitAmount = 0.95861141853499998,
                            UnitAbbreviation = "OZ",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 18,
                            CompareUnitAbbreviation = "PT",
                            CompareUnitAmount = 0.052042100000000001,
                            UnitAbbreviation = "OZ",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 19,
                            CompareUnitAbbreviation = "QT",
                            CompareUnitAmount = 0.03125,
                            UnitAbbreviation = "OZ",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 20,
                            CompareUnitAbbreviation = "GAL",
                            CompareUnitAmount = 0.0078125,
                            UnitAbbreviation = "OZ",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 21,
                            CompareUnitAbbreviation = "G",
                            CompareUnitAmount = 236.58823648491,
                            UnitAbbreviation = "C",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 22,
                            CompareUnitAbbreviation = "OZ",
                            CompareUnitAmount = 8.3454044514869992,
                            UnitAbbreviation = "C",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 23,
                            CompareUnitAbbreviation = "C",
                            CompareUnitAmount = 1.0,
                            UnitAbbreviation = "C",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 24,
                            CompareUnitAbbreviation = "LB",
                            CompareUnitAmount = 0.52158777821799995,
                            UnitAbbreviation = "C",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 25,
                            CompareUnitAbbreviation = "TBSP",
                            CompareUnitAmount = 16.0,
                            UnitAbbreviation = "C",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 26,
                            CompareUnitAbbreviation = "TSP",
                            CompareUnitAmount = 48.0,
                            UnitAbbreviation = "C",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 27,
                            CompareUnitAbbreviation = "FL OZ",
                            CompareUnitAmount = 8.0,
                            UnitAbbreviation = "C",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 28,
                            CompareUnitAbbreviation = "PT",
                            CompareUnitAmount = 0.5,
                            UnitAbbreviation = "C",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 29,
                            CompareUnitAbbreviation = "QT",
                            CompareUnitAmount = 0.25,
                            UnitAbbreviation = "C",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 30,
                            CompareUnitAbbreviation = "GAL",
                            CompareUnitAmount = 0.0625,
                            UnitAbbreviation = "C",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 31,
                            CompareUnitAbbreviation = "G",
                            CompareUnitAmount = 453.59237000000002,
                            UnitAbbreviation = "LB",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 32,
                            CompareUnitAbbreviation = "OZ",
                            CompareUnitAmount = 16.0,
                            UnitAbbreviation = "LB",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 33,
                            CompareUnitAbbreviation = "C",
                            CompareUnitAmount = 1.917222837193,
                            UnitAbbreviation = "LB",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 34,
                            CompareUnitAbbreviation = "LB",
                            CompareUnitAmount = 1.0,
                            UnitAbbreviation = "LB",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 35,
                            CompareUnitAbbreviation = "TBSP",
                            CompareUnitAmount = 30.675565391454001,
                            UnitAbbreviation = "LB",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 36,
                            CompareUnitAbbreviation = "TSP",
                            CompareUnitAmount = 92.026696174362002,
                            UnitAbbreviation = "LB",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 37,
                            CompareUnitAbbreviation = "FL OZ",
                            CompareUnitAmount = 15.337782696563,
                            UnitAbbreviation = "LB",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 38,
                            CompareUnitAbbreviation = "PT",
                            CompareUnitAmount = 0.95861141853499998,
                            UnitAbbreviation = "LB",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 39,
                            CompareUnitAbbreviation = "QT",
                            CompareUnitAmount = 0.47930570926799998,
                            UnitAbbreviation = "LB",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 40,
                            CompareUnitAbbreviation = "GAL",
                            CompareUnitAmount = 0.11982642731699999,
                            UnitAbbreviation = "LB",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 41,
                            CompareUnitAbbreviation = "G",
                            CompareUnitAmount = 14.786764782056,
                            UnitAbbreviation = "TBSP",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 42,
                            CompareUnitAbbreviation = "OZ",
                            CompareUnitAmount = 0.52158777828000003,
                            UnitAbbreviation = "TBSP",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 43,
                            CompareUnitAbbreviation = "C",
                            CompareUnitAmount = 0.0625,
                            UnitAbbreviation = "TBSP",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 44,
                            CompareUnitAbbreviation = "LB",
                            CompareUnitAmount = 0.032599236141999999,
                            UnitAbbreviation = "TBSP",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 45,
                            CompareUnitAbbreviation = "TBSP",
                            CompareUnitAmount = 1.0,
                            UnitAbbreviation = "TBSP",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 46,
                            CompareUnitAbbreviation = "TSP",
                            CompareUnitAmount = 3.0,
                            UnitAbbreviation = "TBSP",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 47,
                            CompareUnitAbbreviation = "FL OZ",
                            CompareUnitAmount = 0.5,
                            UnitAbbreviation = "TBSP",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 48,
                            CompareUnitAbbreviation = "PT",
                            CompareUnitAmount = 0.03125,
                            UnitAbbreviation = "TBSP",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 49,
                            CompareUnitAbbreviation = "QT",
                            CompareUnitAmount = 0.015625,
                            UnitAbbreviation = "TBSP",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 50,
                            CompareUnitAbbreviation = "GAL",
                            CompareUnitAmount = 0.0039060000000000002,
                            UnitAbbreviation = "TBSP",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 51,
                            CompareUnitAbbreviation = "G",
                            CompareUnitAmount = 4.9289215940190001,
                            UnitAbbreviation = "TSP",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 52,
                            CompareUnitAbbreviation = "OZ",
                            CompareUnitAmount = 0.17386259275999999,
                            UnitAbbreviation = "TSP",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 53,
                            CompareUnitAbbreviation = "C",
                            CompareUnitAmount = 0.020833000000000001,
                            UnitAbbreviation = "TSP",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 54,
                            CompareUnitAbbreviation = "LB",
                            CompareUnitAmount = 0.010866412047,
                            UnitAbbreviation = "TSP",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 55,
                            CompareUnitAbbreviation = "TBSP",
                            CompareUnitAmount = 0.33333299999999999,
                            UnitAbbreviation = "TSP",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 56,
                            CompareUnitAbbreviation = "TSP",
                            CompareUnitAmount = 1.0,
                            UnitAbbreviation = "TSP",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 57,
                            CompareUnitAbbreviation = "FL OZ",
                            CompareUnitAmount = 0.16666700000000001,
                            UnitAbbreviation = "TSP",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 58,
                            CompareUnitAbbreviation = "PT",
                            CompareUnitAmount = 0.010416999999999999,
                            UnitAbbreviation = "TSP",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 59,
                            CompareUnitAbbreviation = "QT",
                            CompareUnitAmount = 0.005208,
                            UnitAbbreviation = "TSP",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 60,
                            CompareUnitAbbreviation = "GAL",
                            CompareUnitAmount = 0.001302,
                            UnitAbbreviation = "TSP",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 61,
                            CompareUnitAbbreviation = "G",
                            CompareUnitAmount = 29.573529562499999,
                            UnitAbbreviation = "FL OZ",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 62,
                            CompareUnitAbbreviation = "OZ",
                            CompareUnitAmount = 1.043175556502,
                            UnitAbbreviation = "FL OZ",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 63,
                            CompareUnitAbbreviation = "C",
                            CompareUnitAmount = 0.125,
                            UnitAbbreviation = "FL OZ",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 64,
                            CompareUnitAbbreviation = "LB",
                            CompareUnitAmount = 0.065198472280999994,
                            UnitAbbreviation = "FL OZ",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 65,
                            CompareUnitAbbreviation = "TBSP",
                            CompareUnitAmount = 2.0,
                            UnitAbbreviation = "FL OZ",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 66,
                            CompareUnitAbbreviation = "TSP",
                            CompareUnitAmount = 6.0,
                            UnitAbbreviation = "FL OZ",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 67,
                            CompareUnitAbbreviation = "FL OZ",
                            CompareUnitAmount = 1.0,
                            UnitAbbreviation = "FL OZ",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 68,
                            CompareUnitAbbreviation = "PT",
                            CompareUnitAmount = 0.0625,
                            UnitAbbreviation = "FL OZ",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 69,
                            CompareUnitAbbreviation = "QT",
                            CompareUnitAmount = 0.03125,
                            UnitAbbreviation = "FL OZ",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 70,
                            CompareUnitAbbreviation = "GAL",
                            CompareUnitAmount = 0.0078120000000000004,
                            UnitAbbreviation = "FL OZ",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 71,
                            CompareUnitAbbreviation = "G",
                            CompareUnitAmount = 473.17647299999999,
                            UnitAbbreviation = "PT",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 72,
                            CompareUnitAbbreviation = "OZ",
                            CompareUnitAmount = 16.690808904038999,
                            UnitAbbreviation = "PT",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 73,
                            CompareUnitAbbreviation = "C",
                            CompareUnitAmount = 2.0,
                            UnitAbbreviation = "PT",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 74,
                            CompareUnitAbbreviation = "LB",
                            CompareUnitAmount = 1.043175556502,
                            UnitAbbreviation = "PT",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 75,
                            CompareUnitAbbreviation = "TBSP",
                            CompareUnitAmount = 32.0,
                            UnitAbbreviation = "PT",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 76,
                            CompareUnitAbbreviation = "TSP",
                            CompareUnitAmount = 96.0,
                            UnitAbbreviation = "PT",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 77,
                            CompareUnitAbbreviation = "FL OZ",
                            CompareUnitAmount = 16.0,
                            UnitAbbreviation = "PT",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 78,
                            CompareUnitAbbreviation = "PT",
                            CompareUnitAmount = 1.0,
                            UnitAbbreviation = "PT",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 79,
                            CompareUnitAbbreviation = "QT",
                            CompareUnitAmount = 0.5,
                            UnitAbbreviation = "PT",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 80,
                            CompareUnitAbbreviation = "GAL",
                            CompareUnitAmount = 0.125,
                            UnitAbbreviation = "PT",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 81,
                            CompareUnitAbbreviation = "G",
                            CompareUnitAmount = 946.35294599998997,
                            UnitAbbreviation = "QT",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 82,
                            CompareUnitAbbreviation = "OZ",
                            CompareUnitAmount = 33.381617808077003,
                            UnitAbbreviation = "QT",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 83,
                            CompareUnitAbbreviation = "C",
                            CompareUnitAmount = 4.0,
                            UnitAbbreviation = "QT",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 84,
                            CompareUnitAbbreviation = "LB",
                            CompareUnitAmount = 2.0863511130050001,
                            UnitAbbreviation = "QT",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 85,
                            CompareUnitAbbreviation = "TBSP",
                            CompareUnitAmount = 64.0,
                            UnitAbbreviation = "QT",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 86,
                            CompareUnitAbbreviation = "TSP",
                            CompareUnitAmount = 192.0,
                            UnitAbbreviation = "QT",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 87,
                            CompareUnitAbbreviation = "FL OZ",
                            CompareUnitAmount = 32.0,
                            UnitAbbreviation = "QT",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 88,
                            CompareUnitAbbreviation = "PT",
                            CompareUnitAmount = 2.0,
                            UnitAbbreviation = "QT",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 89,
                            CompareUnitAbbreviation = "QT",
                            CompareUnitAmount = 1.0,
                            UnitAbbreviation = "QT",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 90,
                            CompareUnitAbbreviation = "GAL",
                            CompareUnitAmount = 0.25,
                            UnitAbbreviation = "QT",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 91,
                            CompareUnitAbbreviation = "G",
                            CompareUnitAmount = 3785.4117840007002,
                            UnitAbbreviation = "GAL",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 92,
                            CompareUnitAbbreviation = "OZ",
                            CompareUnitAmount = 133.52647123233001,
                            UnitAbbreviation = "GAL",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 93,
                            CompareUnitAbbreviation = "C",
                            CompareUnitAmount = 16.0,
                            UnitAbbreviation = "GAL",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 94,
                            CompareUnitAbbreviation = "LB",
                            CompareUnitAmount = 8.3454044520210005,
                            UnitAbbreviation = "GAL",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 95,
                            CompareUnitAbbreviation = "TBSP",
                            CompareUnitAmount = 256.0,
                            UnitAbbreviation = "GAL",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 96,
                            CompareUnitAbbreviation = "TSP",
                            CompareUnitAmount = 768.0,
                            UnitAbbreviation = "GAL",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 97,
                            CompareUnitAbbreviation = "FL OZ",
                            CompareUnitAmount = 128.0,
                            UnitAbbreviation = "GAL",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 98,
                            CompareUnitAbbreviation = "PT",
                            CompareUnitAmount = 8.0,
                            UnitAbbreviation = "GAL",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 99,
                            CompareUnitAbbreviation = "QT",
                            CompareUnitAmount = 4.0,
                            UnitAbbreviation = "GAL",
                            UnitAmount = 1.0
                        },
                        new
                        {
                            UnitConversionId = 100,
                            CompareUnitAbbreviation = "GAL",
                            CompareUnitAmount = 1.0,
                            UnitAbbreviation = "GAL",
                            UnitAmount = 1.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
