// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheStockedKitchen.Db;

#nullable disable

namespace TheStockedKitchen.DB.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20230427160205_InitalizeDB")]
    partial class InitalizeDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TheStockedKitchen.Data.Model.FoodStock", b =>
                {
                    b.Property<int>("FoodStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FoodStockId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodStockId"), 1L, 1);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("LastEditedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastEditedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<double>("Quantity")
                        .HasColumnType("float")
                        .HasColumnName("Quantity");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Unit");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("User");

                    b.HasKey("FoodStockId");

                    b.ToTable("FoodStock", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
